---

driver:
  name: vagrant

provisioner:
  name: chef_solo
<% if ENV['CHEF_VERSION'] %>
  require_chef_omnibus: <%= ENV['CHEF_VERSION'] %>
<% end %>
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: centos-6
- name: centos-7
- name: oracle-6
- name: oracle-7
- name: fedora-25
- name: fedora-26
- name: rhel-7

verifier:
  name: inspec
  sudo: true

suites:
  - name: default
    run_list:
      - recipe[cis_rhel::default]
    verifier:
      inspec_tests:
        - https://github.com/dev-sec/cis-dil-benchmark
